version: "3.9"

services:
  frontend:
    build: ./frontend # construit l'image à partir du dossier frontend
    ports:
      - "8080:80" # expose le site sur http://localhost:8080
    depends_on:
      - backend # démarre après le backend
    networks:
      - app-network # connecté au réseau de l'application

# api

  backend:
    build: ./backend # construit l'image backend
    environment:
      - DB_HOST=db 
      - DB_USER=utilisateur1
      - DB_PASSWORD=Password123*
      - DB_NAME=taskdb
    ports:
      - "3000:3000"
    depends_on:
      - db # attend que la base démarre
    networks:
      - app-network # même réseau que frontend et db

# base de données

  db:
    image: postgres:15-alpine # image officielle PostgreSQL
    restart: always # redémarre automatiquement si crash
    environment:
      - POSTGRES_USER=utilisateur1
      - POSTGRES_PASSWORD=Password123*
      - POSTGRES_DB=taskdb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    # pas d'exposition de port donc sécurité respectée

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/rules.yml:/etc/prometheus/rules.yml
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-network

  grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin123
  restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app-network

volumes:
  db-data: # volume nommé garde les données même si container supprimé

networks:
  app-network:
    driver: bridge # réseau Docker isolé