global:
  resolve_timeout: 30s

route:
  receiver: "all-notifications"

receivers:
  - name: "all-notifications"

    # 📩 EMAIL (MailHog ou SMTP)
    email_configs:
      - to: "maellopez51@gmail.com"
        from: "alertmanager@example.com"
        smarthost: "mailhog:1025"
        require_tls: false
        send_resolved: true

  webooks_config:
  - url: "https://discordapp.com/api/webhooks/1517075062967111700/zUmKYlfSzBbTEoRqrdXcF9fssIYgbIpR7xR_I5LlOtyAdcci1LP4SCT6KnXum6lTlGJm"
  send_resolved: true